### ISSUE TITLE
Dragging a window over ToF-E Histogram crashes Potku

### ISSUE THREAD

**Issue by tpitkanen** [JYU-IBA/potku#240]
## Steps to reproduce

1. Open a request
2. Open a measurement
3. Drag a window (Log, Composition changes, Depth profiles, Energy spectra) over the ToF-E Histogram so that the mouse cursor touches the Matplotlib area
4. Potku should crash

Traceback:
```txt
Traceback (most recent call last):
  File "C:\Users\<user>\.virtualenvs\potku-<hash>\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 60, in paintEvent
    memoryview(reg))
  File "C:\Users\<user>\.virtualenvs\potku-<hash>\lib\site-packages\matplotlib\cbook\__init__.py", line 2054, in _unmultiplied_rgba8888_to_premultiplied_argb32
    if alpha8.min() != 0xff:
  File "C:\Users\<user>\.virtualenvs\potku-<hash>\lib\site-packages\numpy\core\_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by tpitkanen** [comment]
The problem has been around since at least 19fb51d8068acae5df325564d1b576ebe0c16f6d. Earlier versions don't work with current global/request settings, so I didn't test them.
